baseURL = "/"
languageCode = "en-us"
title = "Shared Housing Solution"
relativeURLs = true
disableKinds = ["taxonomy", "taxonomyTerm"]


#Menu config file all put here
[menu]
  [[menu.mainmenu]]
   identifier="About"
    name="About"
    url = "/about"
    weight = 2

  [[menu.mainmenu]]
     identifier="Founders"
      name="Founders"
      url = "/founders"
      weight = 3

  [[menu.mainmenu]]
     identifier="Housingmodel"
      name="FAQ"
      url = "/faq"
      weight = 4

  [[menu.mainmenu]]
         identifier="Registration"
          name="registration"
          url = "/registration"
          weight = 5


#Logo put here
[params.logo]
  [[params.logo.item]]
  logo = "logo.svg"
  alt= "Shared Housing Logo"
  URL =""
